# Generated by Django 3.2.15 on 2023-02-20 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
