# Generated by Django 3.2.15 on 2023-02-20 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello_app', '0002_alter_offer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images')),
                ('day', models.IntegerField()),
                ('month', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('sub_title', models.CharField(max_length=100)),
                ('desc', models.TextField()),
            ],
        ),
    ]
